networks:
  unklab:
    external: true

volumes:
  etc_wireguard:

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    pull_policy: always
    container_name: wireguard
    restart: unless-stopped
    volumes:
      - etc_wireguard:/etc/wireguard
    networks:
      - unklab
    environment:
      - LANG=en
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=$$2a$$12$$JKwX2vVjfB4yugoFomJ27uceVHH/VK6yXo9z/F2U/Oy/gOEhw2OBi
      - WG_DEFAULT_ADDRESS=10.7.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
